"""Tests for HTML report generation."""

from datetime import UTC, datetime

import pytest

from review_classification.analysis.outlier_detector import OutlierResult
from review_classification.cli.html_report import generate_html_report
from review_classification.cli.output import RepoClassifyResult


class TestHtmlReportGeneration:
    """Tests for HTML report generation functionality."""

    def test_empty_results(self) -> None:
        """Test HTML report generation with empty results."""
        repo_results: list[RepoClassifyResult] = []
        html = generate_html_report(repo_results)

        assert "<!DOCTYPE html>" in html
        assert "PR Outlier Report" in html
        assert "0" in html  # repos, prs, outliers

    def test_single_repo_with_outliers(self) -> None:
        """Test HTML report with a single repository containing outliers."""
        outlier = OutlierResult(
            pr_id=1,
            pr_number=42,
            title="Large refactor of core module",
            author="alice@example.com",
            merged_at=datetime(2024, 3, 15, tzinfo=UTC),
            is_outlier=True,
            outlier_features=["additions", "code_churn"],
            max_abs_z_score=2.8,
            z_scores={
                "additions": 2.8,
                "deletions": 1.5,
                "code_churn": 2.8,
                "review_duration": None,
            },
        )

        result = RepoClassifyResult(
            repo_name="owner/repo",
            results=[outlier],
            total_prs=100,
        )

        html = generate_html_report([result])

        assert "<!DOCTYPE html>" in html
        assert "owner/repo" in html
        assert "#42" in html
        assert "alice@example.com" in html
        assert "Large refactor of core module" in html
        assert "2.80" in html  # z-score formatted
        assert "additions, code_churn" in html
        assert "https://github.com/owner/repo/pull/42" in html

    def test_multiple_repos_mixed_results(self) -> None:
        """Test HTML report with multiple repositories and mixed success/failure."""
        outlier1 = OutlierResult(
            pr_id=1,
            pr_number=10,
            title="Feature: new endpoint",
            author="bob",
            merged_at=datetime(2024, 3, 10, tzinfo=UTC),
            is_outlier=True,
            outlier_features=["review_duration"],
            max_abs_z_score=3.2,
            z_scores={"review_duration": 3.2},
        )

        result1 = RepoClassifyResult(
            repo_name="owner/repo-a",
            results=[outlier1],
            total_prs=50,
        )

        result2 = RepoClassifyResult(
            repo_name="owner/repo-b",
            error="Sample limit not reached — has only 15 merged PRs, need at least 30",
        )

        html = generate_html_report([result1, result2])

        assert "owner/repo-a" in html
        assert "owner/repo-b" in html
        assert "Sample limit not reached" in html
        assert "#10" in html
        assert "bob" in html

    def test_html_structure_and_styling(self) -> None:
        """Test that HTML report has proper structure and styling."""
        result = RepoClassifyResult(
            repo_name="owner/test-repo",
            results=[],
            total_prs=50,
        )

        html = generate_html_report([result])

        # Check HTML structure
        assert "<html" in html
        assert "</html>" in html
        assert "<head>" in html
        assert "<body>" in html
        assert "<meta charset=" in html
        assert "<style>" in html

        # Check key sections
        assert "<header>" in html
        assert "<footer>" in html
        assert "Generated by" in html

    def test_special_characters_in_title(self) -> None:
        """Test HTML escaping of special characters in PR titles."""
        outlier = OutlierResult(
            pr_id=1,
            pr_number=5,
            title="Fix: <script> injection & 'quotes' issues",
            author="eve",
            merged_at=datetime(2024, 3, 1, tzinfo=UTC),
            is_outlier=True,
            outlier_features=["additions"],
            max_abs_z_score=2.0,
            z_scores={"additions": 2.0},
        )

        result = RepoClassifyResult(
            repo_name="owner/security-repo",
            results=[outlier],
            total_prs=40,
        )

        html = generate_html_report([result])

        # Jinja2 should auto-escape by default
        assert "<script>" not in html or "&lt;script&gt;" in html
        assert "eve" in html

    def test_statistics_calculation(self) -> None:
        """Test that summary statistics are calculated correctly."""
        outliers = [
            OutlierResult(
                pr_id=i,
                pr_number=100 + i,
                title=f"PR {i}",
                author=f"author{i}",
                merged_at=datetime(2024, 3, 1, tzinfo=UTC),
                is_outlier=True,
                outlier_features=["code_churn"],
                max_abs_z_score=2.0 + i * 0.5,
                z_scores={"code_churn": 2.0 + i * 0.5},
            )
            for i in range(5)
        ]

        result = RepoClassifyResult(
            repo_name="owner/multi-outlier",
            results=outliers,
            total_prs=100,
        )

        html = generate_html_report([result])

        # Check summary statistics appear in output
        assert "5" in html  # 5 outliers
        assert "100" in html  # 100 total PRs
        assert "5.0%" in html  # 5% outlier rate

    def test_non_outliers_not_included(self) -> None:
        """Test that non-outlier PRs are not included in the report."""
        outlier = OutlierResult(
            pr_id=1,
            pr_number=1,
            title="Outlier PR",
            author="alice",
            merged_at=datetime(2024, 3, 1, tzinfo=UTC),
            is_outlier=True,
            outlier_features=["additions"],
            max_abs_z_score=2.5,
            z_scores={"additions": 2.5},
        )

        normal_pr = OutlierResult(
            pr_id=2,
            pr_number=2,
            title="Normal PR",
            author="bob",
            merged_at=datetime(2024, 3, 2, tzinfo=UTC),
            is_outlier=False,
            outlier_features=[],
            max_abs_z_score=0.5,
            z_scores={"additions": 0.5},
        )

        result = RepoClassifyResult(
            repo_name="owner/test",
            results=[outlier, normal_pr],
            total_prs=2,
        )

        html = generate_html_report([result])

        # Outlier should be in the table
        assert "Outlier PR" in html
        assert "#1" in html

        # Normal PR should not be in the table (not an outlier)
        assert "Normal PR" not in html
        # But the PR count should reflect both
        assert "2" in html

    def test_null_merged_at_handled(self) -> None:
        """Test that null merged_at dates are handled gracefully."""
        outlier = OutlierResult(
            pr_id=1,
            pr_number=99,
            title="Unmerged PR",
            author="charlie",
            merged_at=None,  # PR not merged
            is_outlier=True,
            outlier_features=["review_duration"],
            max_abs_z_score=1.5,
            z_scores={"review_duration": 1.5},
        )

        result = RepoClassifyResult(
            repo_name="owner/test",
            results=[outlier],
            total_prs=1,
        )

        html = generate_html_report([result])

        assert "—" in html or "—" in html  # em-dash or alternative
        assert "#99" in html
        assert "charlie" in html
